### ISSUE TITLE
Kernel boots on Surface Laptop 3

### ISSUE THREAD

**Issue by mistay** [qzed/linux-surface-kernel#17]
1. cloned this repro https://github.com/qzed/linux-surface-kernel/
2. copied https://github.com/qzed/linux-surface-kernel-configs/debian-5.3-x86_64.config to .config in 1.
3. built w/ gcc (Ubuntu 9.2.1-0ubuntu2)
4. installed kernel and kernel modules, rebooted into new kernel
5. machine stalls at loading ramdisk

running Ubuntu 19.10

microcode version 0x38 (/proc/cpuinfo), kernel dmesg: microcode: sig=0x706e5, pf=0x80, revision=0x38; Microcode Update Driver: v2.2

@qzed is this the way to go? any additional steps required?

**Comment by mistay** [comment]
even tried to (referred from https://github.com/qzed/linux-surface#compiling-the-kernel-from-source, slightly adapted)

1. git clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git ~/linux-stable
2. cd ~/linux-stable
3. git checkout v5.3.y
4. for i in ~/linux-surface/patches/5.3/*.patch; do patch -p1 < $i; done 
5. curl https://raw.githubusercontent.com/qzed/linux-surface-kernel-configs/v5.3/debian-5.3-x86_64.config > .config
5.1. make oldconfig
5.2. make menuconfig -> (no changes) -> EXIT
6. make -j `getconf _NPROCESSORS_ONLN`
7. sudo make install modules_install
8. reboot into new kernel

--> kernel is unable to mount rootfs after timeout of about 30seconds

@qzed, @archseer any ideas to build or run a kernel (config) on a surface laptop 3 to get a system that is capable of insmod'ing the surface_sam.ko to enable a surface laptop 3 keyboard?

**Comment by archseer** [comment]
The ram disk failure sounds like you need to rebuild the initial ramdisk that's used before the kernel boots. I'm not sure how you do that on your system, but on Arch that's done by using mkinitcpio.

**Comment by mistay** [comment]
finally i managed it to compile a vanilla kernel, patched by 
and the following steps:

```1. git clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git ~/linux-stable
2. cd ~/linux-stable
3. git checkout v5.3.y
4. for i in ~/linux-surface/patches/5.3/*.patch; do patch -p1 < $i; done 
5. curl https://raw.githubusercontent.com/qzed/linux-surface-kernel-configs/v5.3/debian-5.3-x86_64.config > .config
5.1. make oldconfig
5.2. make menuconfig -> (no changes) -> EXIT
6. make -j `getconf _NPROCESSORS_ONLN` deb-pkg LOCALVERSION=-linux-surface
7. sudo dpkg -i linux-headers-5.3.11-linux-surface_5.3.11-linux-surface-1_amd64.deb linux-image-5.3.11-linux-surface_5.3.11-linux-surface-1_amd64.deb linux-image-5.3.11-linux-surface-dbg_5.3.11-linux-surface-1_amd64.deb linux-libc-dev_5.3.11-linux-surface-1_amd64.deb
8. reboot into new kernel
```

```Linux ysurfacelinux 5.3.11-linux-surface #1 SMP Wed Nov 13 21:47:32 CET 2019 x86_64 x86_64 x86_64 GNU/Linux
```
i loaded all surface* modules, i.e.

```sudo modprobe surface3_button
sudo modprobe surface3_power
sudo modprobe surface3-wmi
sudo modprobe surfacebook2_dgpu_hps
sudo modprobe surfacepro3_button
sudo modprobe surface_sam_dtx
sudo modprobe surface_sam_san
sudo modprobe surface_sam_sid_gpelid
sudo modprobe surface_sam_sid
sudo modprobe surface_sam_sid_perfmode
sudo modprobe surface_sam_ssh
sudo modprobe surface_sam_vhf
```

```
$ lsmod | grep surf
surface_sam_vhf        20480  0
surface_sam_sid_perfmode    16384  0
surface_sam_dtx        16384  0
surface3_power         16384  0
surface3_button        20480  0
surface_sam_sid_gpelid    20480  0
surfacepro3_button     20480  0
surfacebook2_dgpu_hps    16384  0
surface_sam_sid        16384  0
surface_sam_san        16384  0
surface_sam_ssh        32768  4 surface_sam_sid_perfmode,surface_sam_vhf,surface_sam_dtx,surface_sam_san
crc_ccitt              16384  1 surface_sam_ssh
mfd_core               16384  2 surface_sam_sid,hid_sensor_hub
hid                   143360  7 i2c_hid,surface_sam_vhf,usbhid,hid_multitouch,hid_sensor_hub,intel_ipts,hid_generic
```

but, although surface_sam_vhf is loaded, keyboard's still not responding
