### ISSUE TITLE
Wifi, Bluetooth, Standby and audio not working properly

### ISSUE THREAD

**Issue by enricodarodda** [qzed/linux-surface-kernel#18]
Hi, i have a surface laptop 1st generation, and i have installed on an external box kali linux. I installed the latest kernel version, which is 5.3.10 if I'm not wrong and i encountered some problems actually: after suspension the wifi does not work anymore, and the wifi card is not visible anymore neither from the top bar nor from the terminal (if i run ifconfig); i do have to reboot in order to be able to use it again. 
The Bluetooth does not work out of the box and never worked since my installation. 
Moreover the audio behaves badly, cause when I insert the 3.5mm jack connector of the earphones, the built-in speakers start to reproduce a strange noise.
Another issue is the standby, because sometimes the display just turns off, and if i try to press any button or the track-pad buttons nothing happens; I figured out that I need to press the power button in order to light up the screen but sometimes it doesn't wake up and i need to force the shutdown, which is actually not a good idea, but it's the only thing left to do. However, even if I am able to wake it up, the wifi card doesn't work, so i need to reboot it anyway.
There is also another issue, which is the fact that when you use the Caps Lock key, there is no light, so you don't know if it is enabled or not.

**Comment by qzed** [comment]
As those are multiple issues, let's break them down:

- The wifi issue is a known issue that's being discussed on jakeday/linux-surface. I'll collect some information and open a tracking issue for that here at some point, but at the moment I don't have the time to actively look into this.

- I'm not aware of any bluetooth issues, apart from some configuration stuff. Can you make sure you've got everything installed and set up correctly (IIRC this has been discussed somehwere on jakeday/linux-surface)?

- I'm not aware of any standby issues apart from IPTS issues which should be fixed by the systemd sleep script in qzed/linux-surface. If that doesn't fix it can you get some dmesg logs and open a new issue?

- The caps-lock light is a missing feature due to missing data, which is tracked here: https://github.com/qzed/linux-surfacegen5-acpi/issues/8. There have been some developments and I'll comment with some instructions on something that could help us get the information we need shortly.

**Comment by enricodarodda** [comment]
hi,
thanks for your reply. I wrote down these issues here because on the other project, the latest commit was a long time ago and I didn't know if they were still working on some issues or not. I knew that the wi-fi is a known problem but I asked you anyway because maybe you could have helped me. Looking down at the problems I can attach something if you need, and if you tell how to collect those informations. 
Anyway, I really have the bluetooth problem, which says actually to activate the bluetooth in order to be able to use it, but it is enabled (there is the slider on top of the window to enable/disable it). 
Talking about the standby problem I remember, from the installation process, that there was a message asking to change hibernate with suspend or something like that, is that what you are referring to or is it something else?
ok for the caps lock problem but what about the sound problems with the 3.5 jack-connector inserted?
why did you close this issue anyway?
thanks for you time again, and let me know if I can help or whatever.

**Comment by qzed** [comment]
For the wifi and suspend issues: Can you make sure you are using the latest sleep script (https://github.com/qzed/linux-surface/blob/master/root/lib/systemd/system-sleep/sleep)? There's now also an issue on this repo (#20) which has some additional links to things you can try.

For bluetooth: Can you check https://github.com/jakeday/linux-surface/issues/535, try restarting the bluetooth service (`service bluetooth restart`) and if none of that works check `rfkill`? If none of that works please open a new issue.

**Comment by enricodarodda** [comment]
Thanks for your reply. I just tried the Bluetooth "patches"/"workarounds". I used the above mentioned command (service Bluetooth restart) and it worked, im able to access the Bluetooth, but I couldn't use my headphones, so i installed the package mentioned in the link you posted and started the service; however the Bluetooth now works "properly" there is always an underlying noise, as i have already mentioned and actually the audio quality sucks, i don't know if it is due to my headphones or someone else is having the same problem. 

I looked also at the other link you posted, the one describing the WiFi issues but i cannot understand that much and I' m not able to understand if I'm using the latest script or not. if you are able to write down a guide, that would be awesome. I'm saying that because maybe would enhance debugging.

However thanks for your time and your kindness.

**Comment by qzed** [comment]
For good bluetooth audio quality you'll need to install a pulseaudio plugin (https://github.com/EHfive/pulseaudio-modules-bt). AFAIK it doesn't support the better codecs (aptX/LDAC) by default.

You can re-run the setup script from qzed/linux-surface, that will bring the sleep script to the latest version.

The touchscreen scrolling is an issue of the userspace software (e.g. Gnome, Firefox, or the particular software you're using). For example, there is a flag for Firefox which can enable touch scrolling. You'll have to check that for the software you're experiencing that problem with.

**Comment by enricodarodda** [comment]
I really have to thank you for your support and help, it has been much appreciated. I will try to install the plugin you kindly suggested me and see what happens.

However I am experiencing a lot of crashes lately with my Linux. I don't know if that is you main laptop or not and if that happens to you too; anyway let me know if you do have a stable version.
Again, thank you.

**Comment by enricodarodda** [comment]
sorry if I bother you, I just wanted to ask you another thing: are you aware of any touchpad gestures working with this kernel? I tried to install them and i bricked everything. I had to boot from another pc and remove them. Maybe it was just a conflict while booting, because I activated the "autoload" option or maybe they are incompatible but I don't know actually. Have you ever tried something like that?

**Comment by qzed** [comment]
Linux runs pretty stable for me (apart from the wifi issues which can be mitigated with the script), I'm using the SB2 though.

The touchpad gestures should work out of the box. As far as I know, for Gnome, you will need to run Wayland as they don't support gestures on X11, also you shouldn't need to install anything for them to work.

**Comment by enricodarodda** [comment]
Now that i have updated the kernel to version 5.3.15 works better. By touch-pad gestures do you mean only the scrolling feature with two fingers or also changing the workspace with three fingers and other stuff like that? If I didn't change the default desktop environment, am I using X11?
Another question...when I run the setup.sh, should I need the Xorg pulse audio config files or not? Are those a better way to handle the audio?

**Comment by qzed** [comment]
> By touch-pad gestures do you mean only the scrolling feature with two fingers or also changing the workspace with three fingers and other stuff like that?

I also mean workspace switching (although that's 4 fingers, I think?).

> If I didn't change the default desktop environment, am I using X11?

That depends on your distribution. I don't know. But you can check that (see e.g. https://unix.stackexchange.com/questions/202891/how-to-know-whether-wayland-or-x11-is-being-used).

> Another question...when I run the setup.sh, should I need the Xorg pulse audio config files or not? Are those a better way to handle the audio?

AFAIK those files are supposed to fix some issues with static sounds. You can always try without them and if you have problems install them later. I'd actually recommend this for most of the files, as the devices are a bit different and have their different quirks.

**Comment by enricodarodda** [comment]
Many thanks for your explanation and I'm sorry to bother you again with these kind of questions, it is just that I cannot find a real guide on the internet and it seems like you're a pro. I found out that I'm running x11, and according to what you've said earlier that's the reason why gestures are not working, right? I wanted to know how can I install Wayland, because I have both gnome and gnome classic installed by default, but they are running x11. I found out that I can install wayland and choose the desktop environment from the login screen somehow, but I didn't understand how to do that, can you help me?

**Comment by qzed** [comment]
It should just be that easy. You'll have to figure out what to install for your distribution, install that, and then select the correct session type in your login manager. What you have to install specifically depends on your distribution and you should probably have a look at the wiki there..
