### ISSUE TITLE
What options to choose when compiling the kernel for SB2

### ISSUE THREAD

**Issue by busti** [qzed/linux-surface-kernel#19]
I am trying to compile the kernel using these patches for SB2 13" 8GB for use with debian buster.
I have done the following to apply the patches from this repository
```
cd /opt/linux-stable/
checkout v5.3.10
for i in /opt/linux-surface/patches/5.3/*.patch; do patch -p1 < $i; done
cp /opt/linux-surface/configs/5.1/config .config
make oldconfig
cd ..
dpkg -i linux-headers-5.3.10-surface-linux-surface_5.3.10-surface-linux-surface-1_amd64.deb linux-image-5.3.10-surface-linux-surface_5.3.10-surface-linux-surface-1_amd64.deb linux-libc-dev_5.3.10-surface-linux-surface-1_amd64.deb
```
Since 5.1 a bunch of options have been added. Unfortunately I am quite inexperienced with this so I do not really know what to pick. Right now I apparently picked the wrong options, because my installation does not start at all. I am using a live-install-stick and chroot to fix my system at the moment.  
Is there any update to the process? Should I do something different? What options should I pick? Is there an updated config file?

**Comment by busti** [comment]
Solved. I found the other repository containing the updated config.  
for reference. https://github.com/qzed/linux-surface-kernel-configs

**Comment by qzed** [comment]
The readme on the linux-surface repo is severely outdated and I keep pushing that back, sorry for the confusion this has caused. I've removed the configs from the repo and will update the readme soon.
