### ISSUE TITLE
Would you mind add some aur packages?

### ISSUE THREAD

**Issue by specter119** [qzed/linux-surface-kernel#9]
Thanks for your modifications and the  pre-build kernel and headers in https://github.com/qzed/linux-surface/releases
It is obviously you already have the arch pkgbuild, how about push it to AUR?
Or, the aur helper will warn me that I have some "missing" aur packages.

**Comment by qzed** [comment]
For pre-built packages have a look at https://github.com/qzed/linux-surface/wiki/Package-Repositories#arch-linux-repository. AUR packages are generally for building from source, meaning you would have to build the kernel yourself. (Yes, there are AUR packages with pre-built binaries but they in turn rely on those binaries to be stored somewhere else, which is a bit difficult to achieve with the kernel.)

**Comment by specter119** [comment]
@qzed I have tested your mirror, but it seems that the sever is slower than I directly download them from github. 

Would you mind decompressing your pre-build packages and repack as linux-surface-$ver-qzed-bin, then I can sent it to <https://www.archlinuxcn.org/> then. There is a build bot,  it can track your release updates, and auto update pkgbuild and then rebuild pkg.

**Comment by qzed** [comment]
Sorry, packaging takes me long enough as is right now, and I'd like to focus on development rather than packaging. It is not feasible for me to accommodate every desired packaging format, but if you want to repackage it and upload it somewhere else, feel free to do so.

**Comment by specter119** [comment]
@qzed Thanks for your work.
